/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 SpaceStation.glb
Author: re1monsen (https://sketchfab.com/re1monsen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-station-3-a7a6ad10261149cab31aa394bfcf8940
Title: Space Station 3
*/

import React, { useEffect } from 'react' // Import useEffect
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'; 

export function SpaceStation(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/SpaceStation.glb')
  // 'actions' will contain functions to play/stop/fade animations
  // 'names' is an array of strings with the animation clip names
  const { actions, names } = useAnimations(animations, group)

  // --- Animation Activation Logic ---
  useEffect(() => {
    // Log the names of available animations to the console.
    // This is very helpful for debugging and knowing which animation to play.
    console.log("SpaceStation Animation Clip Names:", names);

    // Check if there are any animations loaded with the model
    if (animations && animations.length > 0) {
      // Attempt to play the first animation clip found.
      // If your model has a specific animation you want (e.g., "Idle", "Spin"),
      // replace `names[0]` with the exact string name, like `actions['Idle']`.
      const firstAnimationName = names[0];

      if (firstAnimationName && actions[firstAnimationName]) {
        console.log(`Playing SpaceStation animation: "${firstAnimationName}"`);
        // Reset the animation, fade it in over 0.5 seconds, and play it.
        // .setLoop(THREE.LoopRepeat) can be added if you want it to loop indefinitely.
        actions[firstAnimationName].reset().fadeIn(0.5).play();
      } else {
        console.warn("No animation actions found for SpaceStation or first action is undefined.");
      }
    } else {
      console.log("No pre-baked animations found in the SpaceStation model.");
    }

    // Cleanup function: This runs when the component unmounts or before the effect re-runs.
    // It stops all active animations to prevent memory leaks.
    return () => {
      Object.values(actions).forEach(action => action.fadeOut(0.5).stop());
    };
  }, [actions, animations, names]); // Dependencies: Re-run effect if these values change

  // Optional: Add a subtle continuous rotation on top of GLTF animations
  // This can give a sense of life even if the GLTF has no animations or for extra movement.
  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.001; // Rotate slowly around the Y-axis
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-2.044, -0.213, -0.061]} scale={2.701}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="SpaceStation_low_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.spacestation_main2} />
              </group>
              <group name="SpaceStation001_low_1">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.spacestation_smalllights} />
              </group>
              <group name="SpaceStation002_low_2">
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.spacestation_main2} />
              </group>
              <group name="SpaceStation003_low_3">
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.spacestation_main2} />
              </group>
              <group name="SpaceStation004_low_4">
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.spacestation_main} />
              </group>
              <group name="SpaceStation005_low_5">
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.spacestation_main} />
              </group>
              <group name="SpaceStation006_low_6" rotation={[Math.PI, -0.545, Math.PI]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.spacestation_main} />
              </group>
              <group name="SpaceStation007_low_7">
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.spacestation_main} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/SpaceStation.glb')
